name: 'npm-otp-publish'
description: 'Action to publish npm pacakges using One-Time Passwords'
branding:
  color: red
  icon: package
inputs:
  npm_user:
    description: 'npm user name'
    required: false
  version_url:
    description: 'version url'
    required: false
  npm_token:
    description: 'npm token'
    required: true
  notifier:
    description: 'notifier to be used'
    required: true
    default: 'github-issue'
  timeout:
    description: 'timeout (in minutes) before the server closes'
    required: true
    default: '15'
  # GitHub Issue notifier options
  github_token:
    description: 'github token (required if notifier is github-issue)'
    required: false
  github_actor:
    description: 'release team to assign the issue'
    required: false
    default: ${{ github.actor }}
  github_release_team:
    description: 'release team to assign the issue'
    required: false
    default: 'github-issue'
  discord_token:
    description: 'discord token (required if notifier is discord)'
    required: false
  discord_channel_id:
    description: 'send the notification to this channel (required if notifier is discord)'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - '--npm-user=${{ inputs.npm_user }}'
    - '--version-url=${{ inputs.version_url }}'
    - '--npm-token=${{ inputs.npm_token }}'
    - '--github-token=${{ inputs.github_token }}'
    - '--notifier=${{ inputs.notifier }}'
    - '--github-actor=${{ inputs.actor }}'
    - '--github-release-team=${{ inputs.release_team }}'
    - '--discord-token=${{ inputs.discord_token }}'
    - '--discord-channel-id=${{ inputs.discord_channel_id }}'
