name: 'npm-otp-publish'
description: 'Action to publish npm pacakges using One-Time Passwords'
inputs:
  npm_user:
    description: 'npm user name'
    required: false
  version_url:
    description: 'version url'
    required: false
  npm_token:
    description: 'npm token'
    required: true
  github_token:  # id of input
    description: 'github token'
    required: true
  notifier:  # id of input
    description: 'notifier to be used'
    required: true
    default: 'github-issue'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - '--npm-user=${{ inputs.npm_user }}'
    - '--version-url=${{ inputs.version_url }}'
    - '--npm-token=${{ inputs.npm_token }}'
    - '--github-token=${{ inputs.github_token }}'
    - '--notifier=${{ inputs.notifier }}'
    - '--repo-url=${{ github.event.repository.html_url }}'
    - '--repo-name=${{ github.repository }}'
