name: 'npm-otp-publish'
description: 'Action to publish npm pacakges using One-Time Passwords'
inputs:
  npm_user:
    description: 'npm user name'
    required: false
  version_url:
    description: 'version url'
    required: false
  npm_token:
    description: 'npm token'
    required: true
  github_token:
    description: 'github token'
    required: true
  notifier:
    description: 'notifier to be used'
    required: true
    default: 'github-issue'
  actor:
    description: 'release team to assign the issue'
    required: true
    default: ${{ github.actor }}
  release_team:
    description: 'release team to assign the issue'
    required: false
    default: 'github-issue'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - '--npm-user=${{ inputs.npm_user }}'
    - '--version-url=${{ inputs.version_url }}'
    - '--npm-token=${{ inputs.npm_token }}'
    - '--github-token=${{ inputs.github_token }}'
    - '--notifier=${{ inputs.notifier }}'
    - '--actor=${{ inputs.actor }}'
    - '--release-team=${{ inputs.release_team }}'
