on:
  push:
    branches:
      - main

name: releaser
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v1.6.3
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
          package-name: '@mmarchini/node-otp-publish'

      - uses: actions/checkout@v2
        if: ${{ steps.release.outputs.release_created }}
      - uses: ./
        if: ${{ steps.release.outputs.release_created }}
        with:
          npm_token: ${{ secrets.NPM_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          version_url: https://github.com/${{ github.repository }}/releases/tag/${{ steps.release.outputs.tag_name }}
          npm_user: mmarchini-bot
          github_actor: ${{ github.actor }}
          github_release_team: mmarchini-oss/collaborators


      # Release to GitHub Marketplace
      - uses: octokit/request-action@v2.x
        id: get_current
        if: ${{ steps.release.outputs.release_created }}
        with:
          # Since it's not possible to publish to the Marketplace via API yet,
          # set the version here manually so we remember to update it on majors
          route: GET /repos/:repository/releases/tags/v0
          repository: ${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: octokit/request-action@v2.x
        id: get_released
        if: ${{ steps.release.outputs.release_created }}
        with:
          route: GET /repos/:repository/releases/tags/:tag
          repository: ${{ github.repository }}
          tag: ${{ steps.release.outputs.tag_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # Since it's not possible to publish to the Marketplace via API yet, set
      # the version here manually so we remember to update it on majors
      - uses: octokit/request-action@v2.x
        if: ${{ steps.release.outputs.release_created }}
        with:
          route: PATCH /repos/:repository/releases/:release_id
          repository: ${{ github.repository }}
          release_id: ${{ fromJson(steps.get_current.outputs.data).id }}
          target_commitish: ${{ fromJson(steps.get_released.outputs.data).target_commitish }}
          body: 'See https://github.com/${{ github.repository }}/releases/tag/${{ steps.release.outputs.tag_name }} for latest changelog'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
